### ISSUE TITLE
[osh-metadata.ttl wikibase review] schema:Person, schema:Organization references

### ISSUE THREAD

**Issue by addshore** [OPEN-NEXT/LOSH#40]
https://github.com/OPEN-NEXT/LOSH/blob/master/osh-metadata.ttl#L207
`schema:Person, schema:Organization` are both referred to in the ontology file for `okh:owner`, however I don't think this ends up helping us figure out the ontology and lining it up with Wikibase.

The implementation of this in terms of ontology in Wikibase probably mean that something like this will happen.
- Property "Owner"
- Items created for each owner?
- These Items have a class that is either "Person" or "Organization"
- These classes in turn need items (and the "class" property must already exist)

I feel this example really emphasizes my main point in #35 where I say that I don't think a TTL file is going to be the best starting point for figuring out how to model this within a Wikibase.

**Comment by moedn** [comment]
alright

- property will be renamed `licensor` to avoid confusion
- `licensor` can be either a person or an organisation
- hence person and organisation are 2 possible ranges of `licensor` whereas only 1 input is allowed (`cardinality=1`)

for the rest see discussion in #35 

let's keep this issue open until #35 is resolved

**Comment by hoijui** [comment]
ok... yes, that is more or less what we imagined (I am sitting together with Martin today).
what exactly would be the problem with this approach?
is it better to have less items/objects/identities in general?

or is the problem this?:
Out of a project on git*hub*, we create an author with a git*hub* IRI, which has name and email as properties. -> `https://github.com/foo/AuthorXY`
Out of a project on git*lab*, we create an author with a git*lab* IRI, which has *the same* name and email as properties. -> `https://gitlab.com/bar/AuthorXY`
Thus it is in fact the same author, but we have two different identities, which is not good.

**Comment by addshore** [comment]
So it looks like your aiming to use classes and subclasses etc to describe your ontology, so one thing that the TTL is currently trying to represent is a class tree.
I feel that a diagram might be the easiest way to come up with this initial tree?

Looking at https://github.com/OPEN-NEXT/LOSH/blob/0ee79f530271239663c30adec91f615d6af41b20/osh-metadata.ttl#L184-L192 this seems to be easier to follow now.

> Thus it is in fact the same author, but we have two different identities, which is not good.

That indeed seems like a problem that you will need to try to solve.
This is one of the example reconciliation points that we may need to figure out.

In this case email can be assumed to be unique among authors (I hope) so reconciliation can be done around that?
In the example you mention you would indeed want to end up with 1 entity to represent both the author on github and gitlab.

**Comment by moedn** [comment]
We just had an 'internal reconciliation' about that :)

For v1.0 we won't track user's contributions or make users identifiable 

- GDPR: just because user data (such as eMail) is publicly available via the GitHub API, doesn't mean that we can store, process and publish it somewhere else (e.g. on Wikibase) without their consent
- answering the question: "what are other (OSH) projects of this person _on this platform" can be answered on that platform (e.g. GitHub); this would be just a comfortable, but not a new feature
- new feature would be to track contributions/project ownerships of users across different platforms; making users identifiable is a prerequisite of course. This however seems a) to fall rather under the umbrella of @penyuan 's work (although he's focused on GitHub) and b) to be a fairly intense, yet optional task. I propose we build a working version first and keep this as an optional extension of our work. This is surely a cool feature. Once we have a v1.0 published we'll see if developing it is worth the effort (or if e.g. @penyuan already took care of it in the meantime)

→ so:

- no reconciliation needed
- knowing the licensor is essential (legal information), knowing that two different licensor identities are the same person is optional

Seems that this issue can be closed now; if anything remained unanswered, please reopen it again.
