### ISSUE TITLE
shorten `label` for visualisation

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH#43]
visualisation tools use `rdfs:label`.
Thus, those names should be short, so they do not bloat the visualisation.

**Comment by hoijui** [comment]
nice!
I did not know that.. good!
Maybe `rdfs:comment` for longer things then?

... would you also suggest to not use white-space in `rdfs:label` (example we have: `rdfs:label "OSH meta-data"`)?
probably OK, right?

**Comment by hoijui** [comment]
will work on this now...

**Comment by moedn** [comment]
> ... would you also suggest to not use white-space in `rdfs:label` (example we have: `rdfs:label "OSH meta-data"`)?

What's the issue with white-spaces?

**Comment by hoijui** [comment]
if it should be used to create variable names in a programming language, white-spaces would be bad, but after talking today, I think that is not the scope of `rdfs:label`; it is rather for human friendly displaying, and thus we should ignore this comment of mine.

I would say, this issue is solved now.
